### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by anissen** [kevinresol/craftinginterpreters#1]
Hi, this is a great implementation of _jlox_. It's very clean and makes great use of algebraic data types to represent the abstract syntax tree.

I have a handful of improvements and additions I would like to make. I'll make some pull requests. 

I've also set up a validation system with a small library of lox-scripts. I want to run those as unit tests instead -- do you have any preference in unit testing libraries?

In the longer run, I would also like to
* set up some simple continuous integration testing
* set up a Haxe check-style config to allow for automatically formatting the code according to that configuration
* set up VSCode configurations for building, running, debugging etc.
* link to this repo from the official "crafting interpreters" repo
* personally, I want to branch off a make a small hobby language with this repo as base

**Comment by anissen** [comment]
I'll continue work on my own implementation in my fork as per https://github.com/kevinresol/craftinginterpreters/pull/6#issuecomment-562132908.

**Comment by kevinresol** [comment]
Thanks for your efforts anyway 😉
